-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.db_category
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT db_category_pkey PRIMARY KEY (id),
    CONSTRAINT db_category_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.db_complaint
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cause character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    submission_date timestamp with time zone NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT db_complaint_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.db_opinion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    content text COLLATE pg_catalog."default",
    rating integer NOT NULL,
    user_id bigint NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT db_opinion_pkey PRIMARY KEY (id),
    CONSTRAINT unique_user_product_opinion UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.db_order
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date_order timestamp with time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT db_order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.db_order_product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT db_order_product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.db_photo_product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    path character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT db_photo_product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.db_product
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    old_price numeric(10, 2),
    description text COLLATE pg_catalog."default",
    sale_id bigint,
    CONSTRAINT db_product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.db_product_category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    category_id integer NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT db_product_category_pkey PRIMARY KEY (id),
    CONSTRAINT db_product_category_product_id_category_id_79a3a0ca_uniq UNIQUE (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS public.db_product_tags
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    product_id integer NOT NULL,
    tag_id bigint NOT NULL,
    CONSTRAINT db_product_tags_pkey PRIMARY KEY (id),
    CONSTRAINT db_product_tags_product_id_tag_id_a2342cd4_uniq UNIQUE (product_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.db_sale
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    discount_amount numeric(5, 2) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    CONSTRAINT db_sale_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.db_specification
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    parameter_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    specification text COLLATE pg_catalog."default",
    product_id integer NOT NULL,
    CONSTRAINT db_specification_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.db_tag
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT db_tag_pkey PRIMARY KEY (id),
    CONSTRAINT db_tag_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.db_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(10) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT db_user_pkey PRIMARY KEY (id),
    CONSTRAINT db_user_email_key UNIQUE (email),
    CONSTRAINT db_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.db_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT db_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT db_user_groups_user_id_group_id_4e607823_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.db_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT db_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT db_user_user_permissions_user_id_permission_id_ff552965_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.home_cartitem
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    quantity integer NOT NULL,
    product_id integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT home_cartitem_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.method_product_demand_forecast
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    forecast_period character varying(10) COLLATE pg_catalog."default" NOT NULL,
    period_start date NOT NULL,
    expected_demand numeric(10, 2) NOT NULL,
    demand_variance numeric(10, 2) NOT NULL,
    reorder_point integer NOT NULL,
    suggested_stock_level integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT method_product_demand_forecast_pkey PRIMARY KEY (id),
    CONSTRAINT method_product_demand_fo_product_id_forecast_peri_a38cca57_uniq UNIQUE (product_id, forecast_period, period_start)
);

CREATE TABLE IF NOT EXISTS public.method_product_sentiment_summary
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    average_sentiment_score numeric(5, 3) NOT NULL,
    positive_count integer NOT NULL,
    neutral_count integer NOT NULL,
    negative_count integer NOT NULL,
    total_opinions integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT method_product_sentiment_summary_pkey PRIMARY KEY (id),
    CONSTRAINT method_product_sentiment_summary_product_id_key UNIQUE (product_id)
);

CREATE TABLE IF NOT EXISTS public.method_product_similarity
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    similarity_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    similarity_score numeric(5, 3) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product1_id integer NOT NULL,
    product2_id integer NOT NULL,
    CONSTRAINT method_product_similarity_pkey PRIMARY KEY (id),
    CONSTRAINT method_product_similarit_product1_id_product2_id__434735a6_uniq UNIQUE (product1_id, product2_id, similarity_type)
);

CREATE TABLE IF NOT EXISTS public.method_productassociation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    support double precision NOT NULL,
    confidence double precision NOT NULL,
    lift double precision NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_1_id integer NOT NULL,
    product_2_id integer NOT NULL,
    CONSTRAINT home_productassociation_pkey PRIMARY KEY (id),
    CONSTRAINT home_productassociation_product_1_id_product_2_id_eca3d3cc_uniq UNIQUE (product_1_id, product_2_id)
);

CREATE TABLE IF NOT EXISTS public.method_purchase_probability
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    probability numeric(5, 3) NOT NULL,
    confidence_level numeric(5, 3) NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    product_id integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT method_purchase_probability_pkey PRIMARY KEY (id),
    CONSTRAINT method_purchase_probability_user_id_product_id_908a036e_uniq UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.method_recommendation_settings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    active_algorithm character varying(20) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT method_recommendation_settings_pkey PRIMARY KEY (id),
    CONSTRAINT method_recommendation_se_user_id_active_algorithm_5c6537da_uniq UNIQUE (user_id, active_algorithm)
);

CREATE TABLE IF NOT EXISTS public.method_risk_assessment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    risk_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    entity_id integer NOT NULL,
    risk_score numeric(5, 3) NOT NULL,
    confidence numeric(5, 3) NOT NULL,
    mitigation_suggestion text COLLATE pg_catalog."default",
    assessment_date timestamp with time zone NOT NULL,
    CONSTRAINT method_risk_assessment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.method_sales_forecast
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    forecast_date date NOT NULL,
    predicted_quantity integer NOT NULL,
    confidence_interval_lower integer NOT NULL,
    confidence_interval_upper integer NOT NULL,
    historical_accuracy numeric(5, 2),
    created_at timestamp with time zone NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT method_sales_forecast_pkey PRIMARY KEY (id),
    CONSTRAINT method_sales_forecast_product_id_forecast_date_524b4d3f_uniq UNIQUE (product_id, forecast_date)
);

CREATE TABLE IF NOT EXISTS public.method_sentiment_analysis
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sentiment_score numeric(5, 3) NOT NULL,
    sentiment_category character varying(20) COLLATE pg_catalog."default" NOT NULL,
    analyzed_at timestamp with time zone NOT NULL,
    opinion_id bigint NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT method_sentiment_analysis_pkey PRIMARY KEY (id),
    CONSTRAINT method_sentiment_analysis_opinion_id_key UNIQUE (opinion_id)
);

CREATE TABLE IF NOT EXISTS public.method_user_interactions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    interaction_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    product_id integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT method_user_interactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.method_user_product_recommendation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    recommendation_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    score numeric(5, 3) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT method_user_product_recommendation_pkey PRIMARY KEY (id),
    CONSTRAINT method_user_product_reco_user_id_product_id_recom_e9eb391b_uniq UNIQUE (user_id, product_id, recommendation_type)
);

CREATE TABLE IF NOT EXISTS public.method_user_purchase_pattern
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    purchase_frequency numeric(5, 2) NOT NULL,
    average_order_value numeric(10, 2) NOT NULL,
    preferred_time_of_day character varying(20) COLLATE pg_catalog."default" NOT NULL,
    seasonality_factor jsonb,
    last_computed timestamp with time zone NOT NULL,
    category_id integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT method_user_purchase_pattern_pkey PRIMARY KEY (id),
    CONSTRAINT method_user_purchase_pattern_user_id_category_id_24880be2_uniq UNIQUE (user_id, category_id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.db_complaint
    ADD CONSTRAINT db_complaint_order_id_9d6d0b02_fk_db_order_id FOREIGN KEY (order_id)
    REFERENCES public.db_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_complaint_order_id_9d6d0b02
    ON public.db_complaint(order_id);


ALTER TABLE IF EXISTS public.db_opinion
    ADD CONSTRAINT db_opinion_product_id_746fa24a_fk FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_opinion_product_id_746fa24a
    ON public.db_opinion(product_id);


ALTER TABLE IF EXISTS public.db_opinion
    ADD CONSTRAINT db_opinion_product_id_746fa24a_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_opinion_product_id_746fa24a
    ON public.db_opinion(product_id);


ALTER TABLE IF EXISTS public.db_opinion
    ADD CONSTRAINT db_opinion_user_id_e84f8bba_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_opinion_user_id_e84f8bba
    ON public.db_opinion(user_id);


ALTER TABLE IF EXISTS public.db_order
    ADD CONSTRAINT db_order_user_id_d7f23647_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_order_user_id_d7f23647
    ON public.db_order(user_id);


ALTER TABLE IF EXISTS public.db_order_product
    ADD CONSTRAINT db_order_product_order_id_a36cb5d8_fk_db_order_id FOREIGN KEY (order_id)
    REFERENCES public.db_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_order_product_order_id_a36cb5d8
    ON public.db_order_product(order_id);


ALTER TABLE IF EXISTS public.db_order_product
    ADD CONSTRAINT db_order_product_product_id_58cfcbea_fk FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_order_product_product_id_58cfcbea
    ON public.db_order_product(product_id);


ALTER TABLE IF EXISTS public.db_order_product
    ADD CONSTRAINT db_order_product_product_id_58cfcbea_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_order_product_product_id_58cfcbea
    ON public.db_order_product(product_id);


ALTER TABLE IF EXISTS public.db_photo_product
    ADD CONSTRAINT db_photo_product_product_id_bff87291_fk FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_photo_product_product_id_bff87291
    ON public.db_photo_product(product_id);


ALTER TABLE IF EXISTS public.db_photo_product
    ADD CONSTRAINT db_photo_product_product_id_bff87291_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_photo_product_product_id_bff87291
    ON public.db_photo_product(product_id);


ALTER TABLE IF EXISTS public.db_product
    ADD CONSTRAINT db_product_sale_id_97a97b9f_fk_db_sale_id FOREIGN KEY (sale_id)
    REFERENCES public.db_sale (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_product_sale_id_97a97b9f
    ON public.db_product(sale_id);


ALTER TABLE IF EXISTS public.db_product_category
    ADD CONSTRAINT db_product_category_category_id_fb06dae0_fk_db_category_id FOREIGN KEY (category_id)
    REFERENCES public.db_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_product_category_category_id_fb06dae0
    ON public.db_product_category(category_id);


ALTER TABLE IF EXISTS public.db_product_category
    ADD CONSTRAINT db_product_category_product_id_6d985cb4_fk FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_product_category_product_id_6d985cb4
    ON public.db_product_category(product_id);


ALTER TABLE IF EXISTS public.db_product_category
    ADD CONSTRAINT db_product_category_product_id_6d985cb4_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_product_category_product_id_6d985cb4
    ON public.db_product_category(product_id);


ALTER TABLE IF EXISTS public.db_product_tags
    ADD CONSTRAINT db_product_tags_product_id_dc3c88d8_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_product_tags_product_id_dc3c88d8
    ON public.db_product_tags(product_id);


ALTER TABLE IF EXISTS public.db_product_tags
    ADD CONSTRAINT db_product_tags_tag_id_9a153a4c_fk_db_tag_id FOREIGN KEY (tag_id)
    REFERENCES public.db_tag (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_product_tags_tag_id_9a153a4c
    ON public.db_product_tags(tag_id);


ALTER TABLE IF EXISTS public.db_specification
    ADD CONSTRAINT db_specification_product_id_97abe2ba_fk FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_specification_product_id_97abe2ba
    ON public.db_specification(product_id);


ALTER TABLE IF EXISTS public.db_specification
    ADD CONSTRAINT db_specification_product_id_97abe2ba_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_specification_product_id_97abe2ba
    ON public.db_specification(product_id);


ALTER TABLE IF EXISTS public.db_user_groups
    ADD CONSTRAINT db_user_groups_group_id_b432fca5_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_user_groups_group_id_b432fca5
    ON public.db_user_groups(group_id);


ALTER TABLE IF EXISTS public.db_user_groups
    ADD CONSTRAINT db_user_groups_user_id_6ae08316_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_user_groups_user_id_6ae08316
    ON public.db_user_groups(user_id);


ALTER TABLE IF EXISTS public.db_user_user_permissions
    ADD CONSTRAINT db_user_user_permiss_permission_id_f4793bd3_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_user_user_permissions_permission_id_f4793bd3
    ON public.db_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.db_user_user_permissions
    ADD CONSTRAINT db_user_user_permissions_user_id_ca919cec_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS db_user_user_permissions_user_id_ca919cec
    ON public.db_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.home_cartitem
    ADD CONSTRAINT home_cartitem_product_id_27161cd2_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_cartitem_product_id_27161cd2
    ON public.home_cartitem(product_id);


ALTER TABLE IF EXISTS public.home_cartitem
    ADD CONSTRAINT home_cartitem_user_id_71301a85_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_cartitem_user_id_71301a85
    ON public.home_cartitem(user_id);


ALTER TABLE IF EXISTS public.method_product_demand_forecast
    ADD CONSTRAINT method_product_deman_product_id_4e0df472_fk_db_produc FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_product_demand_forecast_product_id_4e0df472
    ON public.method_product_demand_forecast(product_id);


ALTER TABLE IF EXISTS public.method_product_sentiment_summary
    ADD CONSTRAINT method_product_senti_product_id_b25e5b5a_fk_db_produc FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_product_sentiment_summary_product_id_key
    ON public.method_product_sentiment_summary(product_id);


ALTER TABLE IF EXISTS public.method_product_similarity
    ADD CONSTRAINT method_product_similarity_product1_id_635b8d3c_fk_db_product_id FOREIGN KEY (product1_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_product_similarity_product1_id_635b8d3c
    ON public.method_product_similarity(product1_id);


ALTER TABLE IF EXISTS public.method_product_similarity
    ADD CONSTRAINT method_product_similarity_product2_id_9e6c484b_fk_db_product_id FOREIGN KEY (product2_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_product_similarity_product2_id_9e6c484b
    ON public.method_product_similarity(product2_id);


ALTER TABLE IF EXISTS public.method_productassociation
    ADD CONSTRAINT home_productassociation_product_1_id_f7cde933_fk_db_product_id FOREIGN KEY (product_1_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_productassociation_product_1_id_f7cde933
    ON public.method_productassociation(product_1_id);


ALTER TABLE IF EXISTS public.method_productassociation
    ADD CONSTRAINT home_productassociation_product_2_id_178eb83b_fk_db_product_id FOREIGN KEY (product_2_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS home_productassociation_product_2_id_178eb83b
    ON public.method_productassociation(product_2_id);


ALTER TABLE IF EXISTS public.method_purchase_probability
    ADD CONSTRAINT method_purchase_prob_product_id_512098c7_fk_db_produc FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_purchase_probability_product_id_512098c7
    ON public.method_purchase_probability(product_id);


ALTER TABLE IF EXISTS public.method_purchase_probability
    ADD CONSTRAINT method_purchase_probability_user_id_4401d5d3_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_purchase_probability_user_id_4401d5d3
    ON public.method_purchase_probability(user_id);


ALTER TABLE IF EXISTS public.method_recommendation_settings
    ADD CONSTRAINT method_recommendation_settings_user_id_dc3b25cb_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_recommendation_settings_user_id_dc3b25cb
    ON public.method_recommendation_settings(user_id);


ALTER TABLE IF EXISTS public.method_sales_forecast
    ADD CONSTRAINT method_sales_forecast_product_id_245055d0_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_sales_forecast_product_id_245055d0
    ON public.method_sales_forecast(product_id);


ALTER TABLE IF EXISTS public.method_sentiment_analysis
    ADD CONSTRAINT method_sentiment_analysis_opinion_id_aae2f3b8_fk_db_opinion_id FOREIGN KEY (opinion_id)
    REFERENCES public.db_opinion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_sentiment_analysis_opinion_id_key
    ON public.method_sentiment_analysis(opinion_id);


ALTER TABLE IF EXISTS public.method_sentiment_analysis
    ADD CONSTRAINT method_sentiment_analysis_product_id_a7831f54_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_sentiment_analysis_product_id_a7831f54
    ON public.method_sentiment_analysis(product_id);


ALTER TABLE IF EXISTS public.method_user_interactions
    ADD CONSTRAINT method_user_interactions_product_id_d993233a_fk_db_product_id FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_user_interactions_product_id_d993233a
    ON public.method_user_interactions(product_id);


ALTER TABLE IF EXISTS public.method_user_interactions
    ADD CONSTRAINT method_user_interactions_user_id_c5d8ad98_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_user_interactions_user_id_c5d8ad98
    ON public.method_user_interactions(user_id);


ALTER TABLE IF EXISTS public.method_user_product_recommendation
    ADD CONSTRAINT method_user_product__product_id_2fa057f3_fk_db_produc FOREIGN KEY (product_id)
    REFERENCES public.db_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_user_product_recommendation_product_id_2fa057f3
    ON public.method_user_product_recommendation(product_id);


ALTER TABLE IF EXISTS public.method_user_product_recommendation
    ADD CONSTRAINT method_user_product__user_id_24c6df9e_fk_db_user_i FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_user_product_recommendation_user_id_24c6df9e
    ON public.method_user_product_recommendation(user_id);


ALTER TABLE IF EXISTS public.method_user_purchase_pattern
    ADD CONSTRAINT method_user_purchase_category_id_c16915bd_fk_db_catego FOREIGN KEY (category_id)
    REFERENCES public.db_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_user_purchase_pattern_category_id_c16915bd
    ON public.method_user_purchase_pattern(category_id);


ALTER TABLE IF EXISTS public.method_user_purchase_pattern
    ADD CONSTRAINT method_user_purchase_pattern_user_id_94c1630c_fk_db_user_id FOREIGN KEY (user_id)
    REFERENCES public.db_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS method_user_purchase_pattern_user_id_94c1630c
    ON public.method_user_purchase_pattern(user_id);

END;