from django.urls import path
from .views import (
    CategoriesAPIView,
    ProductsAPIView,
    RandomProductsAPIView,
    ProductDetailAPIView,
    home_view,
    UserLoginView,
    UserRegisterView,
    ProductListCreateAPIView,
    ProductRetrieveUpdateDestroyAPIView,
    OrderListAPIView,
    OrderUpdateDestroyAPIView,
    UserListAPIView,
    UserDestroyAPIView,
    ComplaintListCreateAPIView,
    ComplaintRetrieveUpdateDestroyAPIView,
    AdminStatsView,
    CurrentUserView,
    ProductSearchAPIView,
    ClientStatsView,
)

urlpatterns = [
    path("", home_view, name="home"),
    path("api/categories/", CategoriesAPIView.as_view(), name="categories"),
    path("api/random-products/", RandomProductsAPIView.as_view(), name="random-products"),
    path("api/product/<int:pk>/", ProductDetailAPIView.as_view(), name="product-detail"),
    path("api/products-old/", ProductsAPIView.as_view(), name="products"),
    path("api/login/", UserLoginView.as_view(), name="login"),
    path("api/register/", UserRegisterView.as_view(), name="register"),
    path("api/products/", ProductListCreateAPIView.as_view(), name="product-list-create"),
    path("api/products/<int:pk>/", ProductRetrieveUpdateDestroyAPIView.as_view(), name="product-rud"),
    path("api/orders/", OrderListAPIView.as_view(), name="orders-list"),
    path("api/orders/<int:pk>/", OrderUpdateDestroyAPIView.as_view(), name="orders-rud"),
    path("api/users/", UserListAPIView.as_view(), name="users-list"),
    path("api/users/<int:pk>/", UserDestroyAPIView.as_view(), name="users-destroy"),
    path("api/complaints/", ComplaintListCreateAPIView.as_view(), name="complaint-list-create"),
    path("api/complaints/<int:pk>/", ComplaintRetrieveUpdateDestroyAPIView.as_view(), name="complaint-rud"),
    path("api/admin-stats/", AdminStatsView.as_view(), name="admin-stats"),
    path("api/me/", CurrentUserView.as_view(), name="current-user"),
    path("api/search/", ProductSearchAPIView.as_view(), name="product-search"),
    path("api/client-stats/", ClientStatsView.as_view(), name="client-stats"),
]
